# Creating array with np.array function

In [ ]:
# np.array
# 1D array(Vector)
import numpy as np
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [2]:
#2D array(Matrix)
a2=np.array([[1,2],[2,3]])
print(a2)

[[1 2]
 [2 3]]


In [3]:
#3D array(Tensor)
a3=np.array([[[1,2],[2,3]],[[3,4],[5,6]]])
print(a3)

[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]]


In [4]:
#dtype(float)
a1=np.array([1,2,3],dtype=float)
print(a1)

[1. 2. 3.]


In [5]:
#Boolean dtype
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [6]:
#complex dtype
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

# Creating array using np.arange function

In [7]:
#np.arange
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
#alternate numbers
a1=np.arange(1,11,2)
print(a1)

[1 3 5 7 9]


In [9]:
#reshape
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Creating array using np.linspace & np.identity function

In [10]:
#np.linspace(used to generate linearly separable points in a given array)
#maintain same spacing for every element
a=np.linspace(-10,10,10)
print(a)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [11]:
# np.identity(Create identity matrices)
a=np.identity(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Initializing array using np.zeros & np.ones & np.random function

In [12]:
#np.ones
import numpy as np
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# np.zeros
b=np.zeros((2,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# np.random
c=np.random.random((2,3))
print(c)

[[0.42032641 0.97875663 0.74204459]
 [0.70488416 0.42530101 0.01441463]]


# Array Attributes

In [15]:
# ndim(return dimension of array)
import numpy as np
a=np.ndim([[1,2],[2,3]])
print(a)

a1=np.arange(12).reshape(3,4)
print(np.ndim(a1))

a2=np.arange(8).reshape(2,2,2)#(two 2Darray,no of rows ,no of coulmn)
print(np.ndim(a2))

2
2
3


In [16]:
#shape(Return no of elements present in every dimension)
a1=np.arange(1,12)
print(a1.shape)

a2=np.arange(12).reshape(3,4)
print(a2.shape)

a3=np.arange(8).reshape(2,2,2)
print(a3.shape)

(11,)
(3, 4)
(2, 2, 2)


In [17]:
#size(return no of elements present in arrays)
a1=np.arange(8)
print(a1.size)

a2=np.array([[1,2],[3,4]])
print(a2.size)

8
4


In [18]:
#itemsize(size occupied by each and every element)
a1=np.arange(1,13)
print(a1.itemsize)

8


In [19]:
#dtype(Return datatype of items)
a=np.arange(1,13,dtype=np.int32)
print(a.dtype)

b=np.arange(8)
print(b.dtype)

int32
int64


# Changing Datatype

In [20]:
#astype(Changing datatype)
a=np.arange(1,13)
a.astype(np.int32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)