# Array Operation

In [ ]:
# scalar operation (arithmatic operation)
import numpy as np
a1=np.arange(12).reshape(3,4)
print(2*a1)
print(a1**2)
print(a1%2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [ ]:
# scalar operation(Relational operator)
print(a1>5)
print(a1==5)
print(a1<5)
print(a1!=5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False  True False False]
 [False False False False]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [3]:
#Vector operation
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1+a2)
print(a1-a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]


# Array function

In [7]:
import numpy as np
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[36., 82., 31.],
       [32., 24., 39.],
       [30., 93., 20.]])

In [8]:
#max(Return maximum element in array/in particular row or coulmn)
print(a1)
print(np.max(a1))
print(np.max(a1,axis=0))#0->coulmn,1->row

[[36. 82. 31.]
 [32. 24. 39.]
 [30. 93. 20.]]
93.0
[36. 93. 39.]


In [9]:
#min(Return minimum element)
print(np.min(a1))
print(np.min(a1,axis=1))

20.0
[31. 24. 20.]


In [10]:
#sum(return sum of all elements)
print(np.sum(a1))

387.0


In [11]:
#Product(Return product of all elements)
print(np.prod(a1))

152945982259200.0


In [12]:
#mean(Return mean of all elements/element of particular rows or coulmn)
print(np.mean(a1))
print(np.mean(a1,axis=0))

43.0
[32.66666667 66.33333333 30.        ]


In [13]:
#median
print(a1)
print(np.median(a1))
print(np.median(a1,axis=0))

[[36. 82. 31.]
 [32. 24. 39.]
 [30. 93. 20.]]
32.0
[32. 82. 31.]


In [14]:
#standard deviation(std)
print(np.std(a1))
print(np.std(a1,axis=1))


24.517567397911055
[22.9540604   6.12825877 32.31442746]


In [15]:
#variance(var)
print(np.var(a1))
print(np.var(a1,axis=0))

601.1111111111111
[  6.22222222 916.22222222  60.66666667]


In [16]:
#Trigonometric function
from numpy import sin
np,sin(a1)

(<module 'numpy' from 'C:\\Users\\pghos\\AppData\\Roaming\\Python\\Python313\\site-packages\\numpy\\__init__.py'>,
 array([[-0.99177885,  0.31322878, -0.40403765],
        [ 0.55142668, -0.90557836,  0.96379539],
        [-0.98803162, -0.94828214,  0.91294525]]))

In [17]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [18]:
#log/exponents
a4=np.arange(1,13)
print(np.log(a4))
print(np.exp(a4))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]


In [19]:
#round(returns nearest round of integer of float)
import numpy as np
a5=np.random.random((3,3))
print(np.round(a5*100))

[[31. 64. 84.]
 [99. 44.  6.]
 [52. 16. 41.]]


In [20]:
#floor(returns the behind round of integer)
#ceil(return the infront round of integer)
print(np.floor(a5*100))
print(np.ceil(a5*100))

[[31. 63. 84.]
 [99. 44.  5.]
 [52. 16. 41.]]
[[ 32.  64.  85.]
 [100.  45.   6.]
 [ 53.  17.  42.]]


# Indexing and Slicing

In [35]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [36]:
#indexing(2D)
a2
print(a2[1,2])

6


In [37]:
#3D (indexing)
print(a3)
print(a3[0,1,1])
print(a3[1,1,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
7


In [38]:
#Slicing(1D)
print(a1)
print(a1[0:5])
print(a1[0:5:2])
print(a1[::2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 2 4]
[0 2 4 6 8]


In [39]:
#Slicing(2D)
print(a2)
print(a2[0,:])#1st row
print(a2[:,0])#1st coulmn
print(a2[1:,1:3])
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[1,::3])
print(a2[:2,1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[0 4 8]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [40]:
print(a2[::2,1:3])
print(a2[::2,::3])
print(a2[1:3,:3:2])
print(a2[:2,1::2])

[[ 1  2]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 4  6]
 [ 8 10]]
[[1 3]
 [5 7]]


In [41]:
print(a2[::2,1:3])
print(a2[1:,1:3])
print(a2[1:,::3])
print(a2[:2,::3])

[[ 1  2]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 4  7]
 [ 8 11]]
[[0 3]
 [4 7]]


In [46]:
#Slicing(3D)
a=np.arange(27).reshape(3,3,3)
print(a)
print(a[1])
print(a[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [44]:
#slicing(3D)
print(a[0,1:])
print(a[1,:,1])
print(a[2,1:,1:])
print(a[::2,0,::2])

[[3 4 5]
 [6 7 8]]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


# Iterating

In [69]:
#1D array
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [70]:
#2D Array(print row in every time )
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [71]:
#3D array(print 1 2D array in every time)
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [72]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


# Reshaping/Tranpose/Ravel

In [73]:
#Tranpose
a=np.arange(12).reshape(3,4)
print(np.transpose(a))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [74]:
#Ravel(convert array in 1D)
print(np.ravel(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking

In [75]:
#Horizontal Stacking
b=np.arange(12).reshape(3,4)
c=np.arange(12,24).reshape(3,4)
print(np.hstack((b,c)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [76]:
#Vertical stacking
print(np.vstack((b,c)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Splitting

In [77]:
#Horizontal splitting
print(np.hsplit(b,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [78]:
#Vertical splitting
print(np.vsplit(c,3))

[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
