# np.sort(return a sorted copy of array)

In [2]:
#1D array
import numpy as np
a=np.random.randint(1,100,15)
print(a)
print(np.sort(a))#ascending order
print(np.sort(a,)[::-1])#decending order

[15 71 81 75 24 32 28  8 42 39 61 54 39 80 12]
[ 8 12 15 24 28 32 39 39 42 54 61 71 75 80 81]
[81 80 75 71 61 54 42 39 39 32 28 24 15 12  8]


In [3]:
#2D array
b=np.random.randint(1,100,24).reshape(6,4)
print(b)
print(np.sort(b,axis=0))#column sorting
print(np.sort(b,axis=1))#Row sorting

[[53 70 92 40]
 [69 17 59 46]
 [76 29 58 44]
 [58 88  6 32]
 [17 77 99  1]
 [19 72 93 20]]
[[17 17  6  1]
 [19 29 58 20]
 [53 70 59 32]
 [58 72 92 40]
 [69 77 93 44]
 [76 88 99 46]]
[[40 53 70 92]
 [17 46 59 69]
 [29 44 58 76]
 [ 6 32 58 88]
 [ 1 17 77 99]
 [19 20 72 93]]


# np.append

->appends value along the mentioned axis at the end of the array

In [4]:
#1D array
a=np.array([1,2,3,5,7])
np.append(a,10)

array([ 1,  2,  3,  5,  7, 10])

In [5]:
b

array([[53, 70, 92, 40],
       [69, 17, 59, 46],
       [76, 29, 58, 44],
       [58, 88,  6, 32],
       [17, 77, 99,  1],
       [19, 72, 93, 20]], dtype=int32)

In [6]:
#2D array
b=np.random.randint(1,50,12).reshape(3,4)
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[48., 30., 14., 24.,  1.],
       [15., 48., 22., 42.,  1.],
       [49., 26., 23., 46.,  1.]])

# np.concatenate

->concatenate a sequence of arrays along an existing axis

In [7]:
#2D array
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

print(np.concatenate((a1,a2),axis=0))#Concatenate with column
print(np.concatenate((a1,a2),axis=1))#concatenate with row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


# np.unique

->we can get the unique values from an array given as parameter in np.unique() method

In [8]:
a3=np.array([1,1,1,2,2,2,3,3,4,4,5,5,8,8])
np.unique(a3)

array([1, 2, 3, 4, 5, 8])

# np.expand_dims(expand dimension)

->we can get expanded dimension of an array

In [9]:
a4=np.array([1,2,3,4,5,6])
print(a4.shape)

print(np.expand_dims(a4,axis=0).shape)
print(np.expand_dims(a4,axis=1).shape)

(6,)
(1, 6)
(6, 1)


# np.where

->returns the indices of all elements in an input array where the given condition is satisfied

In [10]:
a=np.random.randint(1,100,24)
print(a)

np.where(a>50)

[27 73 81 63 69  2 64 60 11 92 10  5 38 14 36 44 22 31 47  8 70 20 84  2]


(array([ 1,  2,  3,  4,  6,  7,  9, 20, 22]),)

In [11]:
#replace all values >50 with 0
np.where(a>50,0,a)#(condition,True,False)

array([27,  0,  0,  0,  0,  2,  0,  0, 11,  0, 10,  5, 38, 14, 36, 44, 22,
       31, 47,  8,  0, 20,  0,  2], dtype=int32)

In [12]:
#replace even numbers with 0
np.where(a%2==0,0,a)

array([27, 73, 81, 63, 69,  0,  0,  0, 11,  0,  0,  5,  0,  0,  0,  0,  0,
       31, 47,  0,  0,  0,  0,  0], dtype=int32)

# np.argmax

->return the index of max element of the array in a particular axis

In [13]:
#1D array
a=np.random.randint(1,100,30)
print(a)
print(np.argmax(a))

[46 48 91  4 89 27 47 44 79 86 35 26  7 74 87 39 44 13 67 35 86 42 91 15
 60 30 96 41 36 87]
26


In [14]:
#2D array
b=np.arange(24).reshape(4,6)
print(b)

np.argmax(b,axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([3, 3, 3, 3, 3, 3])

# np.argmin

->return the index of the minimum value of the array in particular axis

In [15]:
print(a)
print(np.argmin(a)) 

[46 48 91  4 89 27 47 44 79 86 35 26  7 74 87 39 44 13 67 35 86 42 91 15
 60 30 96 41 36 87]
3


# np.cumsum

->we can calculate the cumulative sum of array elements over a given axis

In [16]:
#1D array
print(a)
print(np.cumsum(a))

[46 48 91  4 89 27 47 44 79 86 35 26  7 74 87 39 44 13 67 35 86 42 91 15
 60 30 96 41 36 87]
[  46   94  185  189  278  305  352  396  475  561  596  622  629  703
  790  829  873  886  953  988 1074 1116 1207 1222 1282 1312 1408 1449
 1485 1572]


In [17]:
#2D array
print(b)
print(np.cumsum(b,axis=0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  8 10 12 14 16]
 [18 21 24 27 30 33]
 [36 40 44 48 52 56]]


# np.cumprod

->return cumulative product of array elements over a given axis

In [18]:
#1D array
a=np.random.randint(1,100,10)
print(a)

np.cumprod(a)

[87 90 71  7 47 52 92 33 69 27]


array([               87,              7830,            555930,
                 3891510,         182900970,        9510850440,
            874998240480,    28874941935840,  1992370993572960,
       53794016826469920])

In [19]:
#2D array
b=np.random.randint(1,50,24).reshape(4,6)
print(b)

np.cumprod(b,axis=1)

[[42 25 24 14 22  4]
 [ 6 47 26  6 35 48]
 [ 1  9 14  6  2 41]
 [34 28 25 36 35 42]]


array([[        42,       1050,      25200,     352800,    7761600,
          31046400],
       [         6,        282,       7332,      43992,    1539720,
          73906560],
       [         1,          9,        126,        756,       1512,
             61992],
       [        34,        952,      23800,     856800,   29988000,
        1259496000]])

# np.percentile

->used to calculate the nth percentile of the array elements along the speciefic axis

In [20]:
print(a)

print(np.percentile(a,100))#Return max element
print(np.percentile(a,0))#return min element
print(np.percentile(a,50))#return mid element

[87 90 71  7 47 52 92 33 69 27]
92.0
7.0
60.5


# np.histogram

->represents the frequency of data distribution in the graphical form

In [39]:
print(a)
np.histogram(a,bins=[10,20,30,40,50,60,70,80,90,100])

[ 90 100  30  50  60]


(array([0, 0, 1, 0, 1, 1, 0, 0, 2]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

->return pearson product-moment correlation coefficient

In [22]:
salary=np.array([20000,40000,35000,25000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[ 1.        , -0.02816064],
       [-0.02816064,  1.        ]])

# np.isin

->it helps to search more than one element in the same time

In [23]:
import numpy as np
a=np.random.randint(1,100,15)
items=[10,20,50,60,45,78,30]

print(a)
a[np.isin(a,items)]

[70 93 17 20 54 12 27 82 24 44 66 51 90  9 77]


array([20], dtype=int32)

# np.flip

-> reverse the order of array element in a particular axis

In [24]:
# 1D array
a=np.array([10,20,30,50,60])

print(np.flip(a))

[60 50 30 20 10]


In [25]:
#2D array
a1=np.arange(12).reshape(3,4)
print(a1)
np.flip(a1,axis=0)#coulmn element flip

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

# np.put

->it replace speceific array elements with given value.Array indexed worked on fattened array.

In [34]:
print(a)
np.put(a,[0,1],[90,100])
a

[ 90 100  30  50  60]


array([ 90, 100,  30,  50,  60])

# np.delete

->delete the multiple array elements in one time

In [27]:
print(a)
np.delete(a,[0,1,3])

[ 90 100  30  50  60]


array([30, 60])

# set function

In [28]:
# np.union1d
a1=np.array([1,2,3,4,5])
a2=np.array([2,3,4])

np.union1d(a1,a2)

array([1, 2, 3, 4, 5])

In [29]:
#np.intersect1d
np.intersect1d(a1,a2)

array([2, 3, 4])

In [30]:
#np.setdiff1d
np.setdiff1d(a1,a2)

array([1, 5])

In [31]:
#np.setxor1d(return uncommon element)
np.setxor1d(a1,a2)

array([1, 5])

In [32]:
#np.in1d(check the element is present in the array or not)
np.in1d(a1,2)

C:\Users\pghos\AppData\Local\Temp\ipykernel_12000\1630199649.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a1,2)


array([False,  True, False, False, False])

# np.clip

->used to clip (limit) the values in the array

In [37]:
print(a)
np.clip(a,a_min=25,a_max=75)

[ 90 100  30  50  60]


array([75, 75, 30, 50, 60])